
services:
  db:
    image: postgres:latest
    container_name: nestjs
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

